### ISSUE TITLE
加载Router映射错误  好现实 init里面逻辑有问题了。

### ISSUE THREAD

**Issue by mashihao** [iamyours/SimpleRouter#3]
java.lang.RuntimeException: Unable to create application io.github.iamyours.plugins.App: java.lang.RuntimeException: 加载Router映射错误！
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.RuntimeException: 加载Router映射错误！
        at io.github.iamyours.router.RouteMap.loadInto(RouteMap.java:7)
        at io.github.iamyours.router.ARouter.init(ARouter.java:18)
        at io.github.iamyours.plugins.App.onCreate(App.kt:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by iamyours** [comment]
这个错误是默认`RouteMap`类会抛出的，如果报这个错误，说明`RouteMap`没有替换，要么是`RouterPlugin`插件没有启动，要么就是没有`@Route`标记的路由。先看下gradle日志是否含有以下内容：
```
===========route transform finished:
```

**Comment by iamyours** [comment]
windows环境下File的renameTo方法失效导致jar无法覆盖，使得RouteMap类替换失败
