### ISSUE TITLE
生成的路由表class类名错误

### ISSUE THREAD

**Issue by iamyours** [iamyours/SimpleRouter#4]
> 已修复，更新下router-plugin版本号。
> 
> ```
> classpath 'io.github.iamyours:router-plugin:1.0.2'
> ```
> 
> 问题见SimpleRouter项目的[issue #3](https://github.com/iamyours/SimpleRouter/issues/3)

 dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'io.github.iamyours:router-plugin:1.0.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
还是会crash额，看起来要跳转到的explicit activity名称有问题
2019-10-09 11:02:50.018 22324-22324/io.github.iamyours.wandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.iamyours.wandroid, PID: 22324
    android.content.ActivityNotFoundException: Unable to find explicit activity class {io.github.iamyours.wandroid/**iogithubiamyourswandroiduiwebWebActivity**}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1933)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1748)
        at android.app.Activity.startActivityForResult(Activity.java:5168)
        at android.app.Activity.startActivityFromFragment(Activity.java:5144)
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7690)
        at android.app.Fragment.startActivityForResult(Fragment.java:1095)
        at android.app.Fragment.startActivityForResult(Fragment.java:1084)
        at io.github.iamyours.router.Postcard.navigation(Postcard.java:74)
        at io.github.iamyours.router.Postcard.navigation(Postcard.java:79)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb(RouterUtil.kt:21)
        at io.github.iamyours.wandroid.util.RouterUtil.navWeb$default(RouterUtil.kt:13)
        at io.github.iamyours.wandroid.adapter.ArticleAdapter$initView$1.onClick(ArticleAdapter.kt:35)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

_Originally posted by @liyao20190808 in https://github.com/iamyours/Wandroid/issues/2#issuecomment-539800505_

**Comment by iamyours** [comment]
不同操作系统的文件路径分隔符不同导致class类名在某些系统下生成错误。
